sudo: required
language: java

services:
  - docker

env:
  global:
    - secure: dCg1De6oaQ7Rd/JtPd4z3W1HDEIYq3zNm/VOzRe0b0pW37o6Zkv4dROh1jYYf2TbZ3qJdEy6NApumF+iwDy7JSReXiJEQ5OcNny/Kt9Ip2E9f2yXFaVg4rk121p6sXfm1cKC6LPGmvrAsxZmug4cOWLaYCkYAPW3kTmvqeXrKMq+AkD39Jkt/y96y0Vs0xOzvZsV7dUWckVe8mmm1W/Us59f58M4IoXmqxQ+hApSqUCzQciG8JCVfsxXfeZZhwWjkBbGomApgkwkz2JHeIMRCD9pkEen5cG6QHuzg5S2BLNwlt7NLWQO0pEFgeE1U6uKaXaJE7uC7oUPuoQF8VC7xTo1kKjUpr4oWNYuTqmnK8PgrrYfxvyRYB5Zq1tbTy7fhucV5W3K5V64DJY0MFuQC8OrXubYpAisBVXiEQ7XX36NdtDXcXUZFFykPZjbiCmAGwH6Z7HShhWo2fUxQcmmifHpmaSjbCrPtw1Ji5cbWqK/lD6D2kGpMtcmaD0RwZG/48MSt6uZDzwQIc9GunauwKlON9MQ3/3ooOO0fCH/41jxYBgDW0zKA7EnDZe6UwxOy1YdFMHyafLoEaweeHSU9ELj0HJ3QrLYaH8POFEPLfAUeOuRr7TbmgR5G+CzdpI3Md/Ic17Vzh3K2GVLfpsUgX7SMIC7MKoGSmnqoXQc1pw=
    - secure: ZfE3YjLUl7Hz5AvLk7e8ArTm2SUHhGdX8u5TzgdTbG5Us3BKYEEmCT8/98HlWb6hsxEIdS0uCPgPl3e3tYsMdpnmimG7Ltj6U2VpDsEVVZuFkuilcbKSjMsTg5ZQirAdVUM+hJWvvIP4RQ9XB3mefYEbCRSnRFbyv1wbsoJ3o6xxZ8vcWBflihVGScGOoPZ0ndKLqR6XvIhCrlhPmU7okQ9hNYvKBzLj6MqzK1+S7DFY/CqlX7nq2E6X0wvTG6i3+KlQDWJCwMdpeQeZy0J7td2WHcuJiixTZFiLjYsCdjWfKn9HRZ7ebpDGxYSQ2oR6g7mGW+9CeVK9Js1fm8vEUoqqMYFG3HqexiGJZmzT8pTH+wA0j7iiSS+J7d+/fR7to3UnldB9x5hdBiJiic5a7d8Qj7lDtBE67SzjTBV94jcwdnya0e7JYcW3l/c2pefDuvwRb1nDHFz445Bn6PzQREKNuFo5fn0tlBgUB0xMe0xoCgJIpAsS8BOwaDWfDCzMI+jgHVrJUJ2dWO6+xOdcDICGDIwk1aXSMmm5FjZZZm0N8gkehPdlk57R/jayUbWjHt+f71c4aCX5g7/QK/vP5IIn1yTCzJuxofcaslv4cIratP8E3NkKC1eycnVGvjg63xnpTLp6c5jYX/uLCQ/QxKfLrTyo5tHvpRatEp0Q+1E=
    - secure: Bmmf7yVrBFDZeDkSHdmfOMJdyENpCwFCACeH3x44f1zo2JPgHLK53MryS9TkK59XeT2tY1yPHEKkKPTpAIWN+Ki7IPpzGdRTFAIM4q09bzFgBcbe/hX1JlwoNwCjEk7z6xlB7xLjs0YPVg5Q/74o7rdTw1UVpoJTB+egkza/kxL6s9usBfVZ14jVeeadDcgOsCeijGpfpEfkQxVUreQfYrPLEHBJWWMkcLsNm4ksqcfce4VljcjssuanwR/PZgoM4SpBMhKs153e8uv3EeTld5YyQiKTjAcpABHlzGjcZCyo1G4LdLRmPTfOEX++Svd9XF1gsnh5CAcAkhkwGPGb1hSz+L/KFnu9lIWhpT35B54+OTwDRcQQrKkwktSQm7r9X9N+VHfHloKAsgyRP0Q2UDTlmO+LumvpG4kzo8YPEg+RQx6oGcbHUqc0gKGwW0AgT3Tt2Qb4hKP9c1h+Bo7Ko2RS0etCdmwjwmC5QIiA6m/VQZikLPhR70B8NOaWum6Y54t8tDz1Nb7rRMQLQ3JTt0/Qqkenxlwc5cNy9yyrAU8eessn8izapWlrHWL/6CPYv6/vhubct351LEWDEsgTAKQv5QuRhzQORf8MGxY1QpB/xgQngdlaJQtJY7/HZ2YaW+ensTOjvgLDpdIlOHKlwJF/V1ghtOEU2GEBzkNuQlw=

script:
  - mvn package
  - docker build -t howard/dropwizard-demo .

after_success:
  - docker login -e DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=howard/dropwizard-demo
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
